### ISSUE TITLE
Bug: `tal:attributes` might be a dictionary / Chameleon compatibility

### ISSUE THREAD

**Issue by gforcada** [eea/zptlint#6]
Testing `zptlint` in `plone.app.layout` it reports:

```
*** Error in: plone/app/layout/viewlets/anontools.pt
     zope.tal.taldefs.TALError: Bad syntax in attributes: '\n           action'
```

Which is about this tag:

```html
      <a href=""
         tal:content="action/title"
         tal:attributes="
           action;
         "
         i18n:translate=""
      >
```

_Usually_, `tal:attributes` has a syntax of `attribute_name1 value1; attribute_name2 value2`.

But in Chameleon one can pass a dictionary to `tal:attributes` and they are expanded without a problem. See the [Chameleon documentation](https://chameleon.readthedocs.io/en/latest/reference.html#tal-attributes) on the paragraph that says:

```text
If an attribute statement is just an expression, it must evaluate to a Python dict (or implement the methods update() and items() from the dictionary specification).
```

Is `zptlint` using Chameleon by default? 🤔 

Adding `zptlint` as:

```yml
-   repo: https://github.com/eea/zptlint
    rev: 579c9bc35a859e0a309bb8b1d0e35bf990dcab39
    hooks:
    -   id: zptlint
        additional_dependencies:
          - five.pt
```

i.e. installing it as a pre-commit hook and adding `five.pt` as a dependency, to trigger the conditional import of Chameleon, leads to:

```
*** Error in: plone/app/layout/viewlets/social_tags_body.pt
     builtins.TypeError: PathExpr.__init__() missing 2 required positional arguments: 'expr' and 'engine'
```

Implying that it is not really compatible with Chameleon? 🤔
